
site_name: Easy_ETL Documentation

nav:
  - Home: index.md
  - Pipeline: pipeline.md

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'image/etl_prosses_schema.png'
  favicon: 'image/etl_prosses_schema.png'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - codehilite

